routes/web.php
<?php

use GuzzleHttp\Client;
use App\Http\Controllers\UserController;
//use SoapClient;



/** Cancelaciones*/
Route::resource('companias', CompaniaController::class)->middleware('auth');
Route::resource('beneficiarios', BeneficiarioController::class)->middleware('auth'); 
Route::resource('financieras', FinancieraController::class)->middleware('auth'); 
Route::resource('estados', EstadoController::class)->middleware('auth'); 
Route::resource('observaciones', ObservacioneController::class)->middleware('auth'); 
Route::resource('motivcancelaciones', MotivcancelacioneController::class)->middleware('auth'); 
Route::resource('scancelaciones', ScancelacioneController::class)->middleware('auth');
Route::resource('activosoattarifas', ActivosoattarifaController::class)->middleware('auth');
Route::resource('mispolizas', MispolizaController::class)->middleware('auth');
Route::post('consulta', 'ScancelacioneController@consulta')->name('consulta')->middleware('auth');


/** Soat */
Route::post('license-plate', 'SoatController@licensePlate')->name('licenseplate');
Route::get('license-plate', 'SoatController@licensePlate')->name('licenseplate');
Route::post('license-plate-prueba', 'SoatController@licensePlateprueba')->name('licenseplateprueba');
Route::get('license-plate-prueba', 'SoatController@licensePlateprueba')->name('licenseplateprueba');
Route::post('operation-car', 'SoatController@operationCar')->name('operationcar');
Route::get('operation-car', 'SoatController@operationCar')->name('operationcar');
Route::post('operation-car-prueba', 'SoatController@operationCarprueba')->name('operationcarprueba');
Route::get('operation-car-prueba', 'SoatController@operationCarprueba')->name('operationcarprueba');
Route::get('new-insurance-policy-budget', 'SoatController@newInsurancePolicyBudget')->name('newInsurancePolicyBudget');
Route::post('new-insurance-policy-budget', 'SoatController@newInsurancePolicyBudget')->name('newInsurancePolicyBudget');
Route::post('user-data', 'SoatController@userData')->name('userdata');
Route::post('user-data-prueba', 'SoatController@userDataprueba')->name('userdataprueba');
Route::get('operacion-nacional', 'SoatController@nationalOperation')->name('nationalOperation');
Route::get('operacion-nacional-prueba', 'SoatController@nationalOperationprueba')->name('nationalOperationprueba');
Route::get('type-document', 'SoatController@typeDocument')->name('typeDocument');
Route::get('new-insurance-policy-budget-prueba', 'SoatController@newInsurancePolicyBudgetprueba')->name('newInsurancePolicyBudgetprueba');
Route::post('new-insurance-policy-budget-prueba', 'SoatController@newInsurancePolicyBudgetprueba')->name('newInsurancePolicyBudgetprueba');




/** AXA */
Route::post('cotizar-poliza', 'AxaController@policyQuote')->name('consultar_poliza');
Route::get('cotizar-poliza', 'AxaController@policyQuote')->name('consultar_poliza');
Route::post('imprimir-cotizacion', 'AxaController@printPolicy')->name('imprimir_cotizacion');
Route::get('imprimir-cotizacion', 'AxaController@printPolicy')->name('imprimir_cotizacion');
Route::post('emision-poliza', 'AxaController@policyEmission')->name('emision_poliza');
Route::get('emision-poliza', 'AxaController@policyEmission')->name('emision_poliza');

/** Purchases */
Route::post('purchase', 'PaymentController@purchase')->name('purchase');
Route::get('purchase', 'PaymentController@purchase')->name('purchase');
Route::post('payment', 'PaymentController@payment')->name('payment');
Route::get('payment', 'PaymentController@payment')->name('payment');
Route::post('soat-pagos', 'PaymentController@multicash')->name('policyQuote');


Route::post('purchase-Prueba', 'PaymentController@purchasePrueba')->name('purchasePrueba');
Route::get('purchase-Prueba', 'PaymentController@purchasePrueba')->name('purchasePrueba');
// Route::post('api', 'SoatController@licensePlate')->name('api');
/*Route::get('/api', function () {
	//$client = new GuzzleHttp\Client();
	//$client = new Client([
	//	'base_uri' => 'https://pre.transfiriendo.com:448/SOATNETSEAPI/api/Vehicle/GetVehicle?NumberPlate=emt040',
	//]);
	$client = new GuzzleHttp\Client();
	$response = $client->request('GET', 'https://pre.transfiriendo.com:448/SOATNETSEAPI/api/Vehicle/GetVehicle?NumberPlate=emt040',[
			'headers'=> [
				'Client' => ['987654059'],
				'Authorization' => ['bearer 390E27347EF0F703A95C6176C316556D3D8D4999-7811646'],
			]
		]);
	//$test = json_decode($response, true);

	$data =  json_decode( $response->getBody()->getContents() );
	return $data;
});*/


Route::get('/divisas', function () {
	$opts = array(
		'ssl' => array('chipers'=> 'RCA-SHA', 'verify_peer'=> false , 'verify_peer_name'=>false)
	);
	$params = array("moneda" => "2");
	//$url = "https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx?wsdl";
	$url = "https://tmms.axacolpatria.co:3275/AXAColpatria/GestionPolizas/CotizacionPolizaAuto/GestionPolizaAuto.svc?Wsdl";
	try{
		//$this->service = InstanceSoapClient::init();
		//dd($client);
		$client = new SoapClient ($url, $opts);
		dd($client);
		$fecha = $client->Variables();
		//$cambio = $client->TipoCambioDia()->TipoCambioDiaResult->CambioDolar->VarDolar->referencia;
		dd($fecha);

	}catch(SoapFault $fault){
		echo '<br>'.$fault;

	}
});
Route::get('servicios', 'AxaController@servicios')->name('servicios');

Route::get('/', function () {
    return view('tienda.index');
});
/* */
Route::get('nosotros', 'HomeController@nosotros')->name('nosotros');
Route::get('inicio', 'HomeController@inicio')->name('inicio');
Route::get('contactenos', 'HomeController@contactenos')->name('contactenos');
Route::get('colmena', 'HomeController@colmena')->name('colmena');
Route::get('contactenos_respuesta', 'HomeController@contactenos')->name('contactenos_respuesta');
Route::get('politica-de-proteccion-de-datos-personales', 'HomeController@policitaprotecciondedatosp')->name('politica-de-proteccion-de-datos-personales');
Route::get('soatsuramericana', 'HomeController@soatsuramericana')->name('soatsuramericana');
Route::get('cotizarsoatsura', 'HomeController@cotizarsoatsura')->name('cotizarsoatsura')->middleware('auth');



Route::get('aseguradoras', 'HomeController@aseguradoras')->name('aseguradoras');
Route::get('todo-riesgo', 'HomeController@riesgo')->name('todo-riesgo');
Route::get('todo-riesgo3', 'HomeController@riesgo3')->name('todo-riesgo3');
Route::post('todo-riesgo3', 'HomeController@riesgo3')->name('todo-riesgo3');
Route::get('soat', 'HomeController@soat')->name('soat');
// Ruta alterna de soat para pruebas
Route::get('soat-test', 'HomeController@soatTest')->name('soat-test');
Route::get('salud', 'HomeController@salud')->name('salud');
Route::get('educativo', 'HomeController@educativo')->name('educativo');
Route::get('personal', 'HomeController@personal')->name('personal');
Route::get('cotizar', 'HomeController@cotizar_todoriesgo')->name('cotizar');
Route::get('mascotas', 'HomeController@mascotas')->name('mascotas');
/*Vida*/
Route::get('vida', 'HomeController@vida')->name('vida');
Route::get('vida_renta', 'HomeController@vida_renta')->name('vida_renta');
Route::get('vida_medida', 'HomeController@vida_medida')->name('vida_medida');
Route::get('vida_mas', 'HomeController@vida_mas')->name('vida_mas');
Route::get('protege_vida', 'HomeController@protege_vida')->name('protege_vida');
Route::get('enfermedades_graves', 'HomeController@enfermedades_graves')->name('enfermedades_graves');
/*endvida*/

Route::get('exequial', 'HomeController@exequial')->name('exequial');
Route::get('hogar', 'HomeController@hogar')->name('hogar');
Route::get('cancelaciones', 'HomeController@cancelaciones')->name('cancelaciones');
Route::get('administrar-cancelaciones', 'HomeController@admincancelaciones')->name('administrar-cancelaciones');
Route::post('enviar-cancelacion', 'HomeController@enviarCancelacion')->name('enviar-cancelacion');

Route::get('pyme', 'HomeController@pyme')->name('pyme');
Route::get('cumplimiento', 'HomeController@cumplimiento')->name('cumplimiento');
Route::get('maquinaria', 'HomeController@maquinaria')->name('maquinaria');
Route::get('construccion', 'HomeController@construccion')->name('construccion');
Route::get('civil', 'HomeController@civil')->name('civil');
Route::get('carga', 'HomeController@carga')->name('carga');
Route::post('registro-cliente', 'HomeController@registro')->name('registro-cliente');

/*Inicio Manejo Email*/
Route::post('enviar-email', 'HomeController@enviarEmailContacto')->name('enviar-email');
Route::post('email-seguro', 'HomeController@enviarEmail')->name('email-seguro');


/*Fin Manejo Email*/
/*Inicio Administrador*/
Route::post('administrador', 'HomeController@administrador')->name('administrador');
Route::get('moduloadministrador', 'HomeController@moduloadministrador')->name('moduloadministrador')->middleware('auth');
Route::get('login', 'HomeController@login')->name('login');
Route::get('registrarse', 'HomeController@registrarse')->name('registrarse');
Route::get('logout', 'HomeController@logout')->name('logout');
Route::get('graficos', 'HomeController@graficos')->name('graficos')->middleware('auth');
Route::get('tablas', 'HomeController@tablas')->name('tablas');
Route::get('reporte-usuarios', 'HomeController@reporte_usuarios')->name('reporte-usuarios')->middleware('auth');
Route::get('detalle-usuario', 'HomeController@detalle_usuario')->name('detalle-usuario')->middleware('auth');
Route::get('detalle-mensaje', 'HomeController@detalle_mensaje')->name('detalle-mensaje');
Route::get('recuperarcontraseña', 'HomeController@recuperarcontrasena')->name('recuperarcontraseña');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Models/Compania.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Compania
 *
 * @property $id
 * @property $nit
 * @property $digito
 * @property $nombre
 * @property $asistencia
 * @property $asistenciafijo
 * @property $activo
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Compania extends Model
{
    
    static $rules = [
		'nit' => 'required',
		'digito' => 'required',
		'nombre' => 'required',
		'asistencia' => 'required',
		'asistenciafijo' => 'required',
		'activo' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nit','digito','nombre','asistencia','asistenciafijo','activo'];



}

app/Http/Controllers/CompaniaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Compania;
use Illuminate\Http\Request;

/**
 * Class CompaniaController
 * @package App\Http\Controllers
 */
class CompaniaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companias = Compania::paginate();

        return view('compania.index', compact('companias'))
            ->with('i', (request()->input('page', 1) - 1) * $companias->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $compania = new Compania();
        return view('compania.create', compact('compania'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Compania::$rules);

        $compania = Compania::create($request->all());

        return redirect()->route('companias.index')
            ->with('success', 'Compania created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $compania = Compania::find($id);

        return view('compania.show', compact('compania'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $compania = Compania::find($id);

        return view('compania.edit', compact('compania'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Compania $compania
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Compania $compania)
    {
        request()->validate(Compania::$rules);

        $compania->update($request->all());

        return redirect()->route('companias.index')
            ->with('success', 'Compania updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $compania = Compania::find($id)->delete();

        return redirect()->route('companias.index')
            ->with('success', 'Compania deleted successfully');
    }
}

resources/views/compania/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Compania
@endsection


@if((Auth::user()->perfil) == 'admin')

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Compania</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('companias.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('compania.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@endif

resources/views/compania/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Compania
@endsection

@if((Auth::user()->perfil) == 'admin')

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Compania</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('companias.update', $compania->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('compania.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@endif

resources/views/compania/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('nit') }}
            {{ Form::text('nit', $compania->nit, ['class' => 'form-control' . ($errors->has('nit') ? ' is-invalid' : ''), 'placeholder' => 'Nit']) }}
            {!! $errors->first('nit', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('digito') }}
            {{ Form::text('digito', $compania->digito, ['class' => 'form-control' . ($errors->has('digito') ? ' is-invalid' : ''), 'placeholder' => 'Digito']) }}
            {!! $errors->first('digito', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $compania->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('asistencia') }}
            {{ Form::text('asistencia', $compania->asistencia, ['class' => 'form-control' . ($errors->has('asistencia') ? ' is-invalid' : ''), 'placeholder' => 'Asistencia']) }}
            {!! $errors->first('asistencia', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('asistenciafijo') }}
            {{ Form::text('asistenciafijo', $compania->asistenciafijo, ['class' => 'form-control' . ($errors->has('asistenciafijo') ? ' is-invalid' : ''), 'placeholder' => 'Asistenciafijo']) }}
            {!! $errors->first('asistenciafijo', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('activo') }}
            {{ Form::text('activo', $compania->activo, ['class' => 'form-control' . ($errors->has('activo') ? ' is-invalid' : ''), 'placeholder' => 'Activo']) }}
            {!! $errors->first('activo', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/compania/index.blade.php
@include('layouts.masteradmin')
@extends('layouts.app')



@if((Auth::user()->perfil) == 'admin')


    @section('content')
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="moduloadministrador">Inicio</a></li>
                            <li class="breadcrumb-item active">Compañias</li>
                        </ol>
                        <!--div class="card mb-4">
                            <div class="card-body">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net/">official DataTables documentation</a>.</div>
                        </div-->
                        <div class="card mb-4">
                            <div class="card-header" style="color:#fff"><i class="fas fa-table mr-1"></i>Compañias</div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Nit</th>
                                                <th>Digito</th>
                                                <th>Nombre</th>
                                                <th>Asistencia</th>
                                                <th>Fijo</th>
                                                <th>Ver</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($companias as $compania)
                                        <tr>
                                            <td>{{ ++$i }}</td>   
											<td>{{ $compania->nit }}</td>
											<td>{{ $compania->digito }}</td>
											<td>{{ $compania->nombre }}</td>
											<td>{{ $compania->asistencia }}</td>
											<td>{{ $compania->asistenciafijo }}</td>
                                            <td>
                                                <form action="{{ route('companias.destroy',$compania->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('companias.show',$compania->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('companias.edit',$compania->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Pronto y Seguros 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                    {!! $companias->links() !!}
                </footer> 
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('admin/js/scripts.js') }}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('admin/assets/demo/datatables-demo.js') }}"></script>
        @endsection 
      
    </body>
</html>




@endif

resources/views/compania/show.blade.php
@extends('layouts.app')
@include('layouts.masteradmin')

@if((Auth::user()->perfil) == 'admin')


<div id="layoutSidenav_content">


@section('content')
    <section class=" container centre">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Compania</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('companias.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nit:</strong>
                            {{ $compania->nit }}
                        </div>
                        <div class="form-group">
                            <strong>Digito:</strong>
                            {{ $compania->digito }}
                        </div>
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $compania->nombre }}
                        </div>
                        <div class="form-group">
                            <strong>Asistencia:</strong>
                            {{ $compania->asistencia }}
                        </div>
                        <div class="form-group">
                            <strong>Asistenciafijo:</strong>
                            {{ $compania->asistenciafijo }}
                        </div>
                        <div class="form-group">
                            <strong>Activo:</strong>
                            {{ $compania->activo }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection


@endif
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('admin/js/scripts.js') }}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('admin/assets/demo/datatables-demo.js') }}"></script>